### ISSUE TITLE
Indentation autofix causing issues with font-face src

### ISSUE THREAD

**Issue by AbdealiJK** [stylelint/awesome-stylelint#33]
### What steps are needed to reproduce the bug?

Create 2 files in any location
```
$ tree -a
.
├── .stylelintrc
└── test.css

0 directories, 2 files
```

Add the following to `test.css`:
```css
@font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 300;
    src: local('Open Sans Light'),
        local('OpenSans-Light'),
        url('/fonts/open-sans-v17-latin-300.woff2') format('woff2'),
        /* Super Modern Browsers */
        url('/fonts/open-sans-v17-latin-300.woff') format('woff'),
        /* Modern Browsers */
        url('/fonts/open-sans-v17-latin-300.ttf') format('truetype'),
        /* Safari, Android, iOS */
        url('/fonts/open-sans-v17-latin-300.svg#OpenSans') format('svg');
}
```

Add the following configs to `.stylelintrc`
```json
{
  "rules": {"indentation": 2}
}
```

Run:
```bash
$ npx stylelint --fix test.css

$ cat test.css
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 300;
  src: local('Open Sans Light'),
    local('OpenSans-Light'),
    url('/assets/open-sans-v17-latin-300.woff2') format('woff2'),

        url('/assets/open-s    latin-300.woff') format('woff'),

        url('/asse    sans-v17-latin-300.ttf    t('truetype'),

        url('/assets/open-sans-v17-lati    g#OpenSans') format('svg')    ;
}
```

The fixed file has invalid CSS - it has removed parts of my url strings and also parts of the `format` etc.

### What did you expect to happen?

I expected it to just fix the indentation

### What actually happened?

No errors - just the output was an invalid CSS file.
